### ISSUE TITLE
.vscode directory shouldnt be part of code

### ISSUE THREAD

**Issue by ShashankaNataraj** [ciscospark/react-ciscospark#481]
Ideally, the .vscode dir should be excluded from github through the .gitignore file

**Comment by bzang** [comment]
@ShashankaNataraj , I would disagree. The workspace .vscode settings file is actually a suggested way, by the VSCode team, to share common workspace settings (see: https://code.visualstudio.com/docs/getstarted/settings)

> Workspace settings are useful for sharing project specific settings across a team.

Because of the way our project is setup, the primary directory where all of our package code, `packages/node_modules`, is ignored by search and file watcher. The settings we provide are a way to get around that.

One thing you can do, if there are settings that you don't like is to create another `.json` settings file in the `.vscode` directory. That should get picked up by VSCode and used.
